@CarInventory_HostAddress = https://localhost:7032

GET {{CarInventory_HostAddress}}/cars

###

POST {{CarInventory_HostAddress}}/cars
Content-Type: application/json
{
    "make": "Toyota",
    "model": "Corola",
    "isavailable": true,
    "secret": "hide info"
}

###

GET {{CarInventory_HostAddress}}/cars/2

###

DELETE {{CarInventory_HostAddress}}/cars/2

###
